version: '3.7'

services:
  frontend:
    image: nginx
    ports:
      - '3000:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./build:/usr/share/nginx/html
    networks:
      - external
networks:
  external:
